import { Footer } from '@/elements/organisms/Footer/index'
import { Header } from '@/elements/organisms/Header/index'
import { Layout } from '@/elements/organisms/Layout/index'

import type { NextPage } from 'next'

import Head from 'next/head'

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header/>
      <Layout/>
      <Footer/>
    </div>
  )
}

export default Home
